#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "drivers/hitechnic-superpro.h"

task comm(){
	//
}

task test(){
	HTSPBsetupIO(HTSPB, 0b11111000);
	while(true){
		HTSPBwriteIO(HTSPB, 0b00001000);
		wait10Msec(100);
		HTSPBwriteIO(HTSPB, 0b00000000);
		wait10Msec(100);
	}
}

task main() {
  StartTask(comm);
  //StartTask(test);
  while(true){wait10Msec(1000);}
}
